global:
  scrape_interval: 1m

alerting:
  alertmanagers:
  - static_configs:
    - targets: 
      - 'alertmanager:9093'

rule_files:
  - "prometheus_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node'
    scrape_interval: 1m
    static_configs:
      - targets: ['node-exporter:9100']
  
  - job_name: 'alertmanager'
    scrape_interval: 1m
    static_configs:
      - targets: ['alertmanager:9093']
